-- EXERCICIO 1
CREATE SCHEMA locadora;
SET search_path TO locadora;
SET datestyle TO 'DMY';

CREATE SEQUENCE cliente_num_seq;

CREATE TABLE CLIENTE (
	numcliente INTEGER DEFAULT nextval('cliente_num_seq') NOT NULL,
	nome VARCHAR(50) NOT NULL,
	endereco VARCHAR(50) NOT NULL,
	foneres VARCHAR(20) NOT NULL,
	fonecel VARCHAR(20) NOT NULL,
	CONSTRAINT PK_CLIENTE
		PRIMARY KEY (numcliente)
);

CREATE SEQUENCE ator_cod_seq;

CREATE TABLE ATOR (
	cod INTEGER DEFAULT nextval('ator_cod_seq') NOT NULL,
	datanasc DATE NOT NULL,
	nacionalidade VARCHAR(50) NOT NULL,
	nomereal VARCHAR(50) NOT NULL,
	nomeartistico VARCHAR(50) NOT NULL,
	CONSTRAINT PK_ATOR
		PRIMARY KEY (cod)
);

CREATE TABLE CLASSIFICACAO (
	cod INTEGER NOT NULL,
	nome VARCHAR(30) CONSTRAINT nomes CHECK (nome = 'super lancamento' OR nome = 'lancamento' OR nome = 'acervo'),
	preco FLOAT NOT NULL,
	CONSTRAINT PK_CLASSIFICACAO
		PRIMARY KEY (cod)
);

CREATE SEQUENCE filme_num_seq;

CREATE TABLE FILME (
	numfilme INTEGER DEFAULT nextval('filme_num_seq') NOT NULL,
	titulo_original VARCHAR(50) NOT NULL,
	titulo_pt VARCHAR(50) NOT NULL,
	duracao INTEGER NOT NULL,
	data_lancamento DATE NOT NULL,
	direcao VARCHAR(50) NOT NULL,
	categoria VARCHAR(50) CONSTRAINT categorias CHECK (categoria = 'drama' OR categoria = 'romance' OR categoria = 'acao' OR categoria = 'comedia'),
	classificacao INTEGER NOT NULL,
	CONSTRAINT PK_FILME
		PRIMARY KEY (numfilme),
	CONSTRAINT FK_FILME
		FOREIGN KEY (classificacao) REFERENCES CLASSIFICACAO(cod)
);

CREATE TABLE MIDIA (
	numfilme INTEGER NOT NULL,
	numero INTEGER NOT NULL,
	tipo VARCHAR(10) CONSTRAINT tipos CHECK (tipo = 'DVD' OR tipo = 'blu-ray'),
	CONSTRAINT PK_MIDIA
		PRIMARY KEY (numfilme, numero, tipo),
	CONSTRAINT FK_MIDIA
		FOREIGN KEY (numfilme) REFERENCES FILME(numfilme)
);

CREATE TABLE ESTRELA (
	numfilme INTEGER NOT NULL,
	codator INTEGER NOT NULL,
	CONSTRAINT PK_ESTRELA
		PRIMARY KEY (numfilme, codator),
	CONSTRAINT FK_ESTRELA
		FOREIGN KEY (numfilme) REFERENCES FILME(numfilme),
	CONSTRAINT FK_ESTRELA2
		FOREIGN KEY (codator) REFERENCES ATOR(cod)
);

CREATE TABLE EMPRESTIMO (
	numfilme INTEGER NOT NULL,
	numero INTEGER NOT NULL,
	tipo VARCHAR(30) NOT NULL,
	cliente INTEGER NOT NULL,
	dataret DATE NOT NULL,
	datadev DATE NOT NULL,
	valor_pg FLOAT,
	CONSTRAINT PK_EMPRESTIMO
		PRIMARY KEY (numfilme, numero, tipo, cliente),
	CONSTRAINT FK_EMPRESTIMO
		FOREIGN KEY (numfilme, numero, tipo) REFERENCES MIDIA(numfilme, numero, tipo),
	CONSTRAINT FK_EMPRESTIMO2
		FOREIGN KEY (cliente) REFERENCES CLIENTE(numcliente)
);


-- EXERCICIO 2
ALTER TABLE EMPRESTIMO DROP CONSTRAINT PK_EMPRESTIMO;
ALTER TABLE EMPRESTIMO DROP CONSTRAINT FK_EMPRESTIMO;
ALTER TABLE EMPRESTIMO DROP CONSTRAINT FK_EMPRESTIMO2;

ALTER TABLE ESTRELA DROP CONSTRAINT PK_ESTRELA;
ALTER TABLE ESTRELA DROP CONSTRAINT FK_ESTRELA;
ALTER TABLE ESTRELA DROP CONSTRAINT FK_ESTRELA2;

ALTER TABLE MIDIA DROP CONSTRAINT PK_MIDIA;
ALTER TABLE MIDIA DROP CONSTRAINT FK_MIDIA;

ALTER TABLE CLIENTE DROP CONSTRAINT PK_CLIENTE;

ALTER TABLE ATOR DROP CONSTRAINT PK_ATOR;

ALTER TABLE FILME DROP CONSTRAINT PK_FILME;
ALTER TABLE FILME DROP CONSTRAINT FK_FILME;

ALTER TABLE CLASSIFICACAO DROP CONSTRAINT PK_CLASSIFICACAO;


-- EXERCICIO 3
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (numcliente);

ALTER TABLE ATOR ADD CONSTRAINT PK_ATOR PRIMARY KEY (cod);

ALTER TABLE FILME ADD CONSTRAINT PK_FILME PRIMARY KEY (numfilme);

ALTER TABLE CLASSIFICACAO ADD CONSTRAINT PK_CLASSIFICACAO PRIMARY KEY (cod);

ALTER TABLE MIDIA ADD CONSTRAINT PK_MIDIA PRIMARY KEY (numfilme, numero, tipo);

ALTER TABLE ESTRELA ADD CONSTRAINT PK_ESTRELA PRIMARY KEY (numfilme, codator);

ALTER TABLE EMPRESTIMO ADD CONSTRAINT PK_EMPRESTIMO PRIMARY KEY (numfilme, numero, tipo, cliente);

ALTER TABLE FILME ADD CONSTRAINT FK_FILME FOREIGN KEY (classificacao) REFERENCES CLASSIFICACAO(cod);

ALTER TABLE MIDIA ADD CONSTRAINT FK_MIDIA FOREIGN KEY (numfilme) REFERENCES FILME(numfilme);

ALTER TABLE ESTRELA ADD CONSTRAINT FK_ESTRELA FOREIGN KEY (numfilme) REFERENCES FILME(numfilme);
ALTER TABLE ESTRELA ADD CONSTRAINT FK_ESTRELA2 FOREIGN KEY (codator) REFERENCES ATOR(cod);

ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO FOREIGN KEY (numfilme, numero, tipo) REFERENCES MIDIA(numfilme, numero, tipo);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO2 FOREIGN KEY (cliente) REFERENCES CLIENTE(numcliente);

-- EXERCICIO 4
INSERT INTO CLASSIFICACAO VALUES (1,'super lancamento',15.00);
INSERT INTO CLASSIFICACAO VALUES (2,'lancamento',10.00);
INSERT INTO CLASSIFICACAO VALUES (3,'acervo',5.00);

INSERT INTO FILME VALUES (1, 'The Godfather', 'O Poderoso Chefão', 175, '24/03/1972', 'Francis Ford Coppola', 'drama', 3);

INSERT INTO midia (numfilme, numero, tipo) VALUES (1, 001, 'DVD');

SELECT * FROM midia;

INSERT INTO CLIENTE (numcliente, nome, endereco, foneres, fonecel) VALUES (1, 'Gabriel', 'alameda oceania, 660', '1234', '5678');
INSERT INTO CLIENTE (numcliente, nome, endereco, foneres, fonecel) VALUES (2, 'Yan', 'segismundo pereira, 410', '9999', '7777');
select * from cliente;
DELETE FROM CLIENTE WHERE numcliente = '3';
