CREATE OR REPLACE FUNCTION FUNC_DADOS_VENDEDOR
	(IN P_CODV VENDEDOR.CODVEND%TYPE, OUT P_NOME VENDEDOR.NOMEVEND%TYPE, OUT SAL FLOAT)
	RETURNS RECORD AS $$
BEGIN
	SELECT NOMEVEND, SALFIXO INTO P_NOME, SAL
	FROM VENDEDOR
	WHERE CODVEND = P_CODV;
END $$ LANGUAGE 'plpgsql';

SELECT * FROM FUNC_DADOS_VENDEDOR (240);
DROP FUNCTION FUNC_DADOS_VENDEDOR

CREATE OR REPLACE FUNCTION FUNC_EXIBE_CLIENTEx ()
RETURNS SETOF CLIENTE AS $$
DECLARE tupla record;
BEGIN
FOR tupla IN SELECT * FROM cliente
LOOP
--processamento sobre o cliente
RETURN NEXT tupla;
END LOOP;
END $$ LANGUAGE 'plpgsql';

SELECT * FROM FUNC_EXIBE_CLIENTEx ();