/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesPrincipais;

import InterfacesSecundarias.*;
import java.awt.Frame;
/**
 *
 * @author gabrielms
 */
public class Home extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    int xMouse2;
    int yMouse2;
    
    cadastrarCliente cadastraCliente = new cadastrarCliente();
    atualizarCliente atualizaCliente = new atualizarCliente();
    acompanharPedido acompanhaPedido = new acompanharPedido();
    adicionarPedido adicionaPedido = new adicionarPedido();
    adicionarVeiculo adicionaVeiculo = new adicionarVeiculo();
    atualizarPedido atualizaPedido = new atualizarPedido();
    atualizarVeiculo atualizaVeiculo = new atualizarVeiculo();
    rastrearVeiculo rastreiaVeiculo = new rastrearVeiculo();
    removerPedido removePedido = new removerPedido();
    removerVeiculo removeVeiculo = new removerVeiculo();
    

    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        abaCliente = new javax.swing.JPanel();
        botaoCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abaPedido = new javax.swing.JPanel();
        botaoPedido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        abaVeiculo = new javax.swing.JPanel();
        botaoVeiculo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        subAbaCliente = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subAbaPedido = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        subAbaVeiculo = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setFocusTraversalPolicyProvider(true);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abaCliente.setBackground(new java.awt.Color(85, 65, 118));
        abaCliente.setMinimumSize(new java.awt.Dimension(340, 40));
        abaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaClienteMouseClicked(evt);
            }
        });
        abaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoClienteMouseClicked(evt);
            }
        });
        abaCliente.add(botaoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer (1).png"))); // NOI18N
        abaCliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 42));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 239, 239));
        jLabel2.setText("CLIENTE");
        abaCliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, -1, -1));

        sidepane.add(abaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 340, 40));

        abaPedido.setBackground(new java.awt.Color(64, 43, 100));
        abaPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPedidoMouseClicked(evt);
            }
        });
        abaPedido.add(botaoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/package.png"))); // NOI18N
        abaPedido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 239, 239));
        jLabel4.setText("PEDIDO");
        abaPedido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, -1, -1));

        sidepane.add(abaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 40));

        abaVeiculo.setBackground(new java.awt.Color(85, 65, 118));
        abaVeiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVeiculoMouseClicked(evt);
            }
        });
        abaVeiculo.add(botaoVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delivery-truck (1).png"))); // NOI18N
        abaVeiculo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, -1, 42));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 239, 239));
        jLabel6.setText("VEÍCULO");
        abaVeiculo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, -1, -1));

        sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transportadora.png"))); // NOI18N
        sidepane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 80));

        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        sidepane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 20));

        subAbaCliente.setBackground(new java.awt.Color(54, 33, 89));
        subAbaCliente.setPreferredSize(new java.awt.Dimension(340, 80));
        subAbaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        subAbaCliente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 230, 10));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        subAbaCliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 239, 239));
        jLabel19.setText("ATUALIZAR CLIENTE");
        subAbaCliente.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 239, 239));
        jLabel20.setText("CADASTRAR CLIENTE");
        subAbaCliente.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        subAbaCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, 40));

        subAbaCliente.setVisible(false);

        sidepane.add(subAbaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        subAbaPedido.setBackground(new java.awt.Color(54, 33, 89));
        subAbaPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 239, 239));
        jLabel25.setText("ADICIONAR PEDIDO");
        subAbaPedido.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 239, 239));
        jLabel26.setText("ATUALIZAR PEDIDO");
        subAbaPedido.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));
        subAbaPedido.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 10));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 239, 239));
        jLabel24.setText("ACOMPANHAR PEDIDO");
        subAbaPedido.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(240, 239, 239));
        jLabel38.setText("REMOVER PEDIDO");
        subAbaPedido.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        subAbaPedido.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 230, 10));
        subAbaPedido.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 10));

        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        subAbaPedido.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        subAbaPedido.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, 40));

        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        subAbaPedido.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 340, 40));

        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        subAbaPedido.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 40));

        subAbaPedido.setVisible(false);

        sidepane.add(subAbaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 340, 160));

        subAbaVeiculo.setBackground(new java.awt.Color(54, 33, 89));
        subAbaVeiculo.setRequestFocusEnabled(false);
        subAbaVeiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(240, 239, 239));
        jLabel30.setText("RASTREAR VEÍCULO");
        subAbaVeiculo.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(240, 239, 239));
        jLabel31.setText("ADICIONAR VEÍCULO");
        subAbaVeiculo.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(240, 239, 239));
        jLabel32.setText("ATUALIZAR VEÍCULO");
        subAbaVeiculo.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(240, 239, 239));
        jLabel39.setText("REMOVER VEÍCULO");
        subAbaVeiculo.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        subAbaVeiculo.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 10));
        subAbaVeiculo.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 230, 10));
        subAbaVeiculo.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 10));

        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        subAbaVeiculo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        subAbaVeiculo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, 40));

        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        subAbaVeiculo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 340, 40));

        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        subAbaVeiculo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 40));

        subAbaVeiculo.setVisible(false);

        sidepane.add(subAbaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 340, 160));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 610));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(54, 33, 89));
        jLabel12.setText(" X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 30, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(54, 33, 89));
        jLabel13.setText(" -");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 30, 20));

        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel10MouseDragged(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 20));

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(painelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 770, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseDragged
        int x2 = evt.getXOnScreen();
        int y2 = evt.getYOnScreen();

        this.setLocation(x2 - xMouse2, y2 - yMouse2);
    }//GEN-LAST:event_jLabel10MouseDragged

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        xMouse2 = evt.getX();
        yMouse2 = evt.getY();
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel11MouseDragged

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void abaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_abaClienteMouseClicked

    
    private void botaoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoClienteMouseClicked
    
        if(subAbaPedido.isVisible()){
            subAbaPedido.setVisible(false);
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));
            
        }
        if(subAbaVeiculo.isVisible()){
            subAbaVeiculo.setVisible(false);
            
        }
        if(subAbaCliente.isVisible()){
            subAbaCliente.setVisible(false);
            sidepane.add(abaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 40));
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));
            
        }
        else{
            sidepane.add(subAbaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 80));
            sidepane.add(abaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150+80, 340, 40));
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190+80, 340, 40));
            
            subAbaCliente.setVisible(true);
        }
    }//GEN-LAST:event_botaoClienteMouseClicked

    private void botaoPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPedidoMouseClicked

        if(subAbaCliente.isVisible()){
            subAbaCliente.setVisible(false);
            sidepane.add(abaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 40));
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));
            
        }
        if(subAbaVeiculo.isVisible()){
            subAbaVeiculo.setVisible(false);
            
        }
        if(subAbaPedido.isVisible()){
            subAbaPedido.setVisible(false);
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));
            
        }
        else{
            sidepane.add(subAbaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150+40, 340, 160));
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190+160, 340, 40));
            
            subAbaPedido.setVisible(true);
        }
    }//GEN-LAST:event_botaoPedidoMouseClicked
    
    private void botaoVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVeiculoMouseClicked

        if(subAbaPedido.isVisible()){
            subAbaPedido.setVisible(false);
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));
            
        }
        if(subAbaCliente.isVisible()){
            subAbaCliente.setVisible(false);
            sidepane.add(abaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 40));
            sidepane.add(abaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));
            
        }
        if(subAbaVeiculo.isVisible()){
            subAbaVeiculo.setVisible(false);
            
        }
        else{
            sidepane.add(subAbaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190+40, 340, 160));
            
            subAbaVeiculo.setVisible(true);
        }
    }//GEN-LAST:event_botaoVeiculoMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(cadastraCliente.isVisible())
            cadastraCliente.setVisible(false);
        else{
            setaSecundariasFalse();
            cadastraCliente.setVisible(true);
            painelPrincipal.add(cadastraCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(atualizaCliente.isVisible())
            atualizaCliente.setVisible(false);
        else{
            setaSecundariasFalse();
            atualizaCliente.setVisible(true);
            painelPrincipal.add(atualizaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if(adicionaPedido.isVisible())
            adicionaPedido.setVisible(false);
        else{
            setaSecundariasFalse();
            adicionaPedido.setVisible(true);
            painelPrincipal.add(adicionaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if(atualizaPedido.isVisible())
            atualizaPedido.setVisible(false);
        else{
            setaSecundariasFalse();
            atualizaPedido.setVisible(true);
            painelPrincipal.add(atualizaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if(removePedido.isVisible())
            removePedido.setVisible(false);
        else{
            setaSecundariasFalse();
            removePedido.setVisible(true);
            painelPrincipal.add(removePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        if(acompanhaPedido.isVisible())
            acompanhaPedido.setVisible(false);
        else{
            setaSecundariasFalse();
            acompanhaPedido.setVisible(true);
            painelPrincipal.add(acompanhaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        if(adicionaVeiculo.isVisible())
            adicionaVeiculo.setVisible(false);
        else{
            setaSecundariasFalse();
            adicionaVeiculo.setVisible(true);
            painelPrincipal.add(adicionaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if(atualizaVeiculo.isVisible())
            atualizaVeiculo.setVisible(false);
        else{
            setaSecundariasFalse();
            atualizaVeiculo.setVisible(true);
            painelPrincipal.add(atualizaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        if(removeVeiculo.isVisible())
            removeVeiculo.setVisible(false);
        else{
            setaSecundariasFalse();
            removeVeiculo.setVisible(true);
            painelPrincipal.add(removeVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        if(rastreiaVeiculo.isVisible())
            rastreiaVeiculo.setVisible(false);
        else{
            setaSecundariasFalse();
            rastreiaVeiculo.setVisible(true);
            painelPrincipal.add(rastreiaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
        }
        validate();
    }//GEN-LAST:event_jLabel23MouseClicked

    public boolean qualquerSecundariaVisivel(){
        if(
        cadastraCliente.isVisible() ||
        atualizaCliente.isVisible() ||
        acompanhaPedido.isVisible() ||
        adicionaPedido.isVisible() ||
        adicionaVeiculo.isVisible() ||
        atualizaPedido.isVisible() ||
        atualizaVeiculo.isVisible() ||
        rastreiaVeiculo.isVisible() ||
        removePedido.isVisible() ||
        removeVeiculo.isVisible()
        )
            return true;
        else
            return false;
    }
    
    public void setaSecundariasFalse(){
        cadastraCliente.setVisible(false);
        atualizaCliente.setVisible(false);
        acompanhaPedido.setVisible(false);
        adicionaPedido.setVisible(false);
        adicionaVeiculo.setVisible(false);
        atualizaPedido.setVisible(false);
        atualizaVeiculo.setVisible(false);
        rastreiaVeiculo.setVisible(false);
        removePedido.setVisible(false);
        removeVeiculo.setVisible(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCliente;
    private javax.swing.JPanel abaPedido;
    private javax.swing.JPanel abaVeiculo;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel botaoCliente;
    private javax.swing.JLabel botaoPedido;
    private javax.swing.JLabel botaoVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel subAbaCliente;
    private javax.swing.JPanel subAbaPedido;
    private javax.swing.JPanel subAbaVeiculo;
    // End of variables declaration//GEN-END:variables
}
